#####################################################
# ______ _                     _____       __       #
# | ___ \ |                   |_   _|     / _|      #
# | |_/ / | __ _ _   _  ___ _ __| | _ __ | |_ ___   #
# |  __/| |/ _` | | | |/ _ \ '__| || '_ \|  _/ _ \  #
# | |   | | (_| | |_| |  __/ | _| || | | | || (_) | #
# \_|   |_|\__,_|\__, |\___|_| \___/_| |_|_| \___/  #
#                 __/ |                             #
#                |___/                              #
#####################################################

settings:
  # Should the plugin be enabled?
  Enable: true

messages:
  info:
    Secret: Secret
    DisplayName: Display Name
    Name: Name
    UUID: UUID
    Gamemode: Gamemode
    World: World
    LocX: X Coord
    LocY: Y Coord
    LocZ: Z Coord
    Food: Food
    Health: Health
    MaxHealth: Maximum Health
    Exp: Exp
    Flying: Flying
    FlySpeed: Fly Speed
    WalkSpeed: WalkSpeed
    Banned: Banned
    Whitelist: Whitelisted
    Online: Online
    Op: Op
    Sprinting: Sprinting
    Sneaking: Sneaking
    Sleeping: Sleeping
    Blocking: Blocking
    InsideVehicle: Inside Vehicle
    Dead: Dead
